//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserTransactions.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserTransactions.Exception.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cpf informado já foi cadastrado..
        /// </summary>
        public static string CpfIsNotUnique {
            get {
                return ResourceManager.GetString("CpfIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cpf é obrigatório..
        /// </summary>
        public static string CpfRequired {
            get {
                return ResourceManager.GetString("CpfRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado já foi cadastrado..
        /// </summary>
        public static string EmailIsNotUnique {
            get {
                return ResourceManager.GetString("EmailIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Email é obrigatório..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome completo é obrigatório..
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo insuficiente..
        /// </summary>
        public static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do cpf é inválido..
        /// </summary>
        public static string InvalidCpfFormat {
            get {
                return ResourceManager.GetString("InvalidCpfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do e-mail é inválido..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida. É preciso ter mais de 6 caracteres..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo de usuário informado é inválido..
        /// </summary>
        public static string InvalidUserType {
            get {
                return ResourceManager.GetString("InvalidUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação não permitida. Lojistas só recebem transferências..
        /// </summary>
        public static string MerchantCannotDebit {
            get {
                return ResourceManager.GetString("MerchantCannotDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do recebedor é obrigatório..
        /// </summary>
        public static string ReceiverIdRequired {
            get {
                return ResourceManager.GetString("ReceiverIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível fazer transação entre carteiras iguais..
        /// </summary>
        public static string SenderAndReceiverMustBeDifferent {
            get {
                return ResourceManager.GetString("SenderAndReceiverMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do remetente é obrigatório..
        /// </summary>
        public static string SenderIdRequired {
            get {
                return ResourceManager.GetString("SenderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da transação precisa ser maior que 0..
        /// </summary>
        public static string TransactionAmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TransactionAmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://httpstatuses.com/{0}.
        /// </summary>
        public static string TypeError {
            get {
                return ResourceManager.GetString("TypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro interno. Entre em contato com nossa equipe para mais informações. Visite: https://github.com/Flaviojcf.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário informado já possui carteira vinculada..
        /// </summary>
        public static string UserAlreadyHasWallet {
            get {
                return ResourceManager.GetString("UserAlreadyHasWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do usuário é obrigatório..
        /// </summary>
        public static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário informado não está cadastrado..
        /// </summary>
        public static string UserNotRegistered {
            get {
                return ResourceManager.GetString("UserNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A carteira do recebedor não existe..
        /// </summary>
        public static string WalletReceiverNotFound {
            get {
                return ResourceManager.GetString("WalletReceiverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A carteira do remetente não existe..
        /// </summary>
        public static string WalletSenderNotFound {
            get {
                return ResourceManager.GetString("WalletSenderNotFound", resourceCulture);
            }
        }
    }
}
