# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests and generate coverage
      run: |
        dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Convert coverage to cobertura format
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
      with:
        reports: 'TestResults/**/coverage.cobertura.xml'
        targetdir: 'CoverageReport'
        reporttypes: 'Cobertura'
        verbosity: 'Info'

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=Flaviojcf_user-transactions
          -Dsonar.organization=flaviojcf
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.cs.opencover.reportsPaths=CoverageReport/Cobertura.xml
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}